#!/usr/bin/env node
/**
 * CLI wrapper around `parse.mjs`'s `buildCatalog`: resolves the two real
 * content roots, builds the catalog, and — given `--emit <path>` — writes
 * it out as a typed TypeScript module the browser panel imports directly
 * (`export const CATALOG: Catalog`), per spec U4/U5's client-bundle-purity
 * gate: this constant, not a runtime data channel, is how the panel gets
 * its 49 roles and 74 commands.
 *
 * Deliberately does not import anything from `src/` or `lib/`: per the
 * task's own gate ordering (`node tools/catalog/build-catalog.mjs --emit
 * ...` runs BEFORE `pnpm build`), `lib/` need not exist yet when this
 * runs, so the content root is recomputed here rather than reusing
 * `src/content.ts`'s compiled `contentDir()`.
 *
 * @module dsh-game-studio/tools/catalog/build-catalog
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildCatalog } from "./parse.mjs";

/**
 * Mirrors `src/content.ts`'s `contentDir()` (absolute path to this
 * package's `content/` tree, trailing slash, forward slashes even on
 * Windows) without importing compiled output — see the module doc for why.
 * @returns {string}
 */
function contentDir() {
  return fileURLToPath(new URL("../../content/", import.meta.url)).replace(/\\/g, "/");
}

/**
 * @param {string[]} argv `process.argv.slice(2)`.
 * @returns {{ emitPath: string }}
 */
function parseArgs(argv) {
  const emitIndex = argv.indexOf("--emit");
  const emitPath = emitIndex === -1 ? undefined : argv[emitIndex + 1];
  if (!emitPath) {
    throw new Error("usage: build-catalog.mjs --emit <path>");
  }
  return { emitPath };
}

/**
 * @param {import("./parse.mjs").Catalog} catalog
 * @returns {string} a complete `.ts` module's source text.
 */
function renderModule(catalog) {
  const lines = [
    "// Generated by tools/catalog/build-catalog.mjs. Do not edit; do not commit.",
    "",
    "export interface CatalogRole {",
    "  role: string;",
    "  description: string;",
    "  tier: number;",
    "  department: string;",
    "  modelTier: string;",
    "  // Content-relative (e.g. \"roles/gameplay-programmer.md\"), never absolute:",
    "  // the content root is a per-installation path and must never end up in a",
    "  // client bundle.",
    "  briefPath: string;",
    "}",
    "",
    "export interface CatalogCommand {",
    "  name: string;",
    "  description: string;",
    "  phase: string;",
    "}",
    "",
    "export interface Catalog {",
    "  roles: CatalogRole[];",
    "  commands: CatalogCommand[];",
    "}",
    "",
    `export const CATALOG: Catalog = ${JSON.stringify(catalog, null, 2)} as const;`,
    "",
  ];
  return lines.join("\n");
}

const { emitPath } = parseArgs(process.argv.slice(2));
const root = contentDir();
const catalog = buildCatalog({ rolesDir: `${root}roles`, skillsDir: `${root}skills`, phaseMapText: undefined });

mkdirSync(dirname(emitPath), { recursive: true });
writeFileSync(emitPath, renderModule(catalog), "utf8");

console.log(`catalog: wrote ${catalog.roles.length} roles, ${catalog.commands.length} commands -> ${emitPath}`);
